@startuml ChangeCredentialsPassword
actor User as usr
participant ResetPasswordEmail as email << Email >>
participant Authentication as spa << Web SPA >>
participant Security as api << Restfull API >>
participant IdentityProvider as idp << Application >>
usr -> email : Click on the link in the email
activate email
email -> spa: Redirect(RecoverCredentialsToken)
deactivate email
activate usr
usr -> usr: Input New Password
usr -> usr: Input Confirm Password
usr -> spa: Call to Action
deactivate usr
activate spa
    spa -> spa: (Validate\npassword and confirm password\nhas input)
    break isInvalid
        spa -> usr: ShowError(InputError)
    end
    spa -> spa: CreatePayload(input)
    spa -> api: DoRequest(payload)
    activate api
        api -> api: ValidateRequest(request)
        break Exception
            api --> spa: Throw BadRequestException
            spa --> usr: ShowError(BadRequest)
        end
        api -> idp: InitRecoveryCredentials(request.payload)
        activate idp
        break Exception
            idp --> api: Throw Exception
            api --> spa: ReturnWithErrors(Exception.message)
            spa --> usr: ShowError(Exception)
        end
        deactivate idp
        api --> spa: ReturnWithSuccess(Message)
    deactivate api
    spa -> usr: ShowSuccess(message)
deactivate spa
@enduml