@startuml ForgotCredentialsPassword
actor User as usr
participant Authentication as spa << Web SPA >>
participant Security as api << Restfull API >>
participant IdentityProvider as idp << Application >>
activate spa
usr -> spa : Select Forgot Password
spa --> usr: ShowForgotPasswordForm
deactivate spa
usr -> spa: Input Username
usr -> spa: Call to Action
activate spa
    spa -> spa: Validate username has input
    break isInvalid
        spa -> usr: ShowError(InputError)
    end
    spa -> spa: CreatePayload(input)
    spa -> api: DoRequest(payload)
    activate api
        api -> api: ValidateRequest(request)
        break Exception
            api --> spa: Throw BadRequestException
            spa --> usr: ShowError(BadRequest)
        end
        api -> idp: InitRecoveryCredentials(request.payload)
        activate idp
        break Exception
            idp --> api: Throw Exception
            api --> spa: ReturnWithErrors(Exception.message)
            spa --> usr: ShowError(Exception)
        end
        deactivate idp
        api --> spa: ReturnWithSuccess(Message)
    deactivate api
    spa -> usr: ShowSuccess(message)
deactivate spa
@enduml