@startuml C4_Context
!include ./plantuml-stdlib/C4/C4_Context.puml

title Context Diagram - Student Answer activity

Person_Ext(student, "Learning Student", "User")
Person(manager, "Learning Manager", "User")
System(learning, "Learning System", "System")
System_Ext(aws, "Aws Cloud", "System")

Rel_R(student, learning, "Start, answer or finish activity")
Rel_L(manager, learning, "Create activity")
Rel(learning, aws, "Use AKS, RDS, Event Bridge, Lambda, S3")

@enduml